#Minecraft server properties
server-port=25570
server-ip=127.0.0.1
enable-rcon=true
rcon.port=25575
rcon.password=pvptrainer
online-mode=false
max-players=10
view-distance=2
pvp=true
difficulty=0
gamemode=2
force-gamemode=true
spawn-npcs=false
spawn-animals=false
spawn-monsters=false
generate-structures=false
level-type=FLAT
generator-settings=
level-name=world
motd=PvP Training Server
network-compression-threshold=-1
use-native-transport=false
enable-command-block=true
allow-flight=true
max-tick-time=-1
connection-throttle=-1
player-idle-timeout=0
white-list=false
resource-pack=
resource-pack-hash=
